config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  default_url_options host: 'http://localhost'
  devise_for :users

  resources :projects do
    resources :tasks, :except => [:index, :new] do
      match "change_status/:status" => 'tasks#change_status', :as => :change_status, :on => :member, :via => :all
      match 'start' => 'tasks#start', :as => 'start', :on => :member, :via => :all
      match 'stop' => 'tasks#stop', :as => 'stop', :on => :member, :via => :all
      resources :comments, :only => [:create, :destroy]
    end
  end


  root :to => 'projects#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :responsible, :class_name => "User"
  belongs_to :status
  belongs_to :type
  belongs_to :estimate
  has_many :comments, :dependent => :destroy
  has_many :task_files, :dependent => :destroy
  has_and_belongs_to_many :watchers, :class_name => "User", :join_table => "tasks_watchers"

  accepts_nested_attributes_for :task_files, :reject_if => lambda { |a| a[:id].blank? and a[:file].blank? }, :allow_destroy => true

  validates :user, :status, :type, :name, :project, :duration_time, :presence => true

  before_save :normalize_description

  STATUSES = {
    todo: 'Todo',
    scheduled: 'Scheduled',
    current: 'Current',
    done: 'Done',
    invalid: 'Invalid'
  }

  TYPES = {
    feature: 'Feature',
    bug: 'Bug'
  }

  scope :todo, ->  { joins(:status).where("statuses.name = '#{STATUSES[:todo]}'") }
  scope :scheduled, -> { joins(:status).where("statuses.name = '#{STATUSES[:scheduled]}'") }
  scope :current, -> { joins(:status).where("statuses.name = '#{STATUSES[:current]}'") }
  scope :done, -> { joins(:status).where("statuses.name = '#{STATUSES[:done]}'") }

  def show_responsible_name
    self.responsible.name rescue 'No responsible yet'
  end

  def show_estimate_name
    self.estimate.name rescue 'No estimative yet'
  end

  def show_type_parameterize_name
    self.type.name.parameterize
  end

  def show_status_parameterize_name
    self.status.name.parameterize
  end

  def normalize_description
    self.description = RedCloth.new(self.description).to_html rescue 'Invalid description format'
  end

  def get_watchers_changes(params)
    unless params.nil?
      current_watchers = []
      watchers.map{ |watch| current_watchers << watch.id.to_s}

      added_watchers = params - current_watchers
      removed_watchers = current_watchers - params

      watchers_changes = {}
      watchers_changes[:added] = []
      watchers_changes[:removed] = []

      added_watchers.each do |add|
        watchers_changes[:added] << add.to_i
      end

      removed_watchers.each do |remove|
        watchers_changes[:removed] << remove.to_i
      end


    end
      watchers_changes
  end

  def get_changes_names(changes)
    field = {:responsible_id => User, :status_id => Status, :type_id => ::Type, :estimate_id => Estimate}
    field.each do |key , value|
      old_name = "None yet"
      new_name = "None yet"

      if changes[key]
        if changes[key].first
          old_name = value.find(changes[key].first).name
        end
        if changes[key].last
          new_name = value.find(changes[key].last).name
        end
      end
      changes[key] = [old_name, new_name]
    end
    changes
  end

  def start_work
    self.start_time = Time.now
    self.save
  end

  def stop_work
    self.duration_time = self.duration_time + ((Time.now.to_i - start_time.to_datetime.to_i) / 60)
    self.start_time = nil
    self.save
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  respond_to :js, :only => [:change_status, :start, :stop]
  before_action :load_users, :load_estimates, :load_status, :load_types, :only => [:new, :create, :edit, :update]
  before_action :load_task, :only => [:show, :edit, :update, :destroy, :change_status, :start, :stop]

  def show
    @comments = @task.comments.all
    @comment = @task.comments.new
  end

  def edit
    project
  end

  def create
    @task = project.tasks.build(task_params[:task])
    @task.user = current_user
    if @task.save
      redirect_to project_task_path(@task.project, @task), notice: 'Task was successfully created.'
    else
      flash[:error] = 'Err... sorry, but something is wrong. :/'
      redirect_to project_path(@task.project.id)
    end
  end

  def update
    @watchers_changes = @task.get_watchers_changes(task_params[:task][:watcher_ids])
    @task.attributes = task_params[:task]
    @task_changes = @task.get_changes_names(@task.changes)

    if @task.save
      Resque.enqueue(TaskMail, @task.id, @task_changes, @watchers_changes)
      redirect_to project_task_path(project,@task), notice: 'Task was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @task.destroy

    redirect_to project_url(@task.project)
  end

  def change_status
    status_id = Status.find_by_name(task_params[:status]).id

    @task.update_attributes(status_id: status_id)
    @task.save

    redirect_to projects_path(@task.project)
  end

  def start
    @task.start_work

    redirect_to project_task_path(@task.project, @task)
  end

  def stop
    @task.stop_work

    redirect_to project_task_path(@task.project, @task)
  end

  private

  def load_task
    @task = project.tasks.find(params[:id])
  end

  def project
    @project ||= current_user.projects.find(params[:project_id])
  end

  def task_params
    params.permit!
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def link_to_show_task(project, task)
    link_to "##{task.id} #{task.type.name} - #{task.name}", project_task_path(project, task),
      :class => "#{task.show_status_parameterize_name} #{task.show_type_parameterize_name}"
  end

  def link_to_time_track(project, task)
    if task.start_time.nil?
      link_to start_project_task_path(project, task), :class => "timer", :remote => true do
        image_tag("ico-timer.png", :class => "icon")+
        "#{task.duration_time}m"
      end
    else
      link_to stop_project_task_path(project, task), :class => "timer active", :remote => true do
        image_tag("ico-timer-active.png", :class => "icon")+
        "#{task.duration_time}m"
      end
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_for([project, task]) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field full">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field full">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field medium">
    <%= f.label :estimate %><br />
    <%= f.collection_select :estimate_id, @estimate, :id, :name, {:prompt => true} %>
  </div>
  <div class="field medium">
    <%= f.label :status %><br />
    <%= f.collection_select :status_id, @status, :id, :name, {:prompt => true} %>
  </div>
  <div class="field medium">
    <%= f.label :type %><br />
    <%= f.collection_select :type_id, @type, :id, :name, {:prompt => true} %>
  </div>
  <div class="field">
    <%= f.label :responsible %><br />
    <%= f.collection_select :responsible_id, @responsibles, :id, :name, {:prompt => true} %>
  </div>
  <div class="field checkbox select-watchers">
    <%= f.label :watchers %>
    <ul>
      <% User.all.each do |w| %>
        <li><label><%= check_box_tag 'task[watcher_ids][]', w.id, task.watchers.include?(w) %><%= w.name %></label></li>
      <% end %>
    </ul>
  </div>
  <h2><%= t(:task_files) %></h2>
  <% fields = f.fields_for(:task_files, TaskFile.new, :child_index => "new_task_files") do |builder| %>
    <%= render("tasks/task_file_fields", :f => builder, :child_index => "new_task_files") %>
  <% end %>
  <%= link_to(t(:add_file), data:{on: :click, call: 'add_fields', args: "[task_files, #{escape_javascript(fields)}]"}) %>
  <div id="task_files">
    <% new_id = Time.now.to_i %>
    <%= f.fields_for :task_files do |task_file| %>
      <%= render :partial => 'task_file_fields', :locals => { :f => task_file, :child_index => new_id} %>
    <% end %>
  </div>
  <br/>
  <%= f.hidden_field :project_id, :value => project.id%>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br/>
<% end %>

app/views/tasks/_task_file_fields.html.erb
<% file_id = "file#{f.object.id ? f.object.id : child_index}" %>
<div class="<%= 'new ' if f.object.new_record? %>task_file" id="<%= file_id %>">
  <% if f.object.new_record? %>
    <%= f.hidden_field :id %>
    <div class="field upload">
      <%= f.label :file %><br />
      <%= f.file_field :file %>
    </div>
  <% else %>
    <div class="field thumb">
      <%= image_tag "task_file.gif" %>
      <%= link_to "Download", f.object.file.url %>
    </div>
  <% end %>
  <div class="field description">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field cover">
    <%= f.hidden_field(:_destroy) %>
    <%= link_to(t(:remove), data: {on: :click, call: 'remove_fields', args: "[#{file_id}]"}, class: "side-link") %>
  </div>
</div>

app/views/tasks/_task_item.html.erb
<li id="task-<%= task.id%>">
  <%= show_user_avatar(task.responsible) %> <%= link_to_time_track(task.project, task) if task.project.time_track %> <%= link_to_show_task(task.project, task) %>
</li>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing ##{@task.id} #{@task.name}" %>
<h1>Editing task</h1>

<%= render :partial => 'form', :locals => {:project => @project, :task => @task} %>

<%= link_to 'Show', [@project,@task] %> |
<%= link_to 'Back', project_task_path %>

app/views/tasks/show.html.erb
<% content_for :title, "##{@task.id} #{@task.name} @ #{@task.project.name}" %>
<article>
  <p><b>Project:</b> <%= link_to @task.project.name, project_path(@task.project) %></p>
  <section id="task-details">
    <h2>#<%= @task.id %> <%= @task.type.name %> - <%= @task.name %></h2>

    <p><b>Owner:</b> <%= show_user_avatar(@task.user) %> <%= @task.user.name %></p>

    <p><b>Responsible:</b> <%= show_user_avatar(@task.responsible) %> <%= @task.show_responsible_name %></p>

    <p><b>Estimate:</b> <%= @task.show_estimate_name %></p>

    <p><b>Status:</b> <%= @task.status.name %></p>

    <p><b>Type:</b> <%= @task.type.name %></p>

    <% if @task.watchers %>
      <b>Watchers:</b>
      <ol class="watchers">
        <% @task.watchers.each do |watcher| %>
          <%= content_tag :li, watcher.name %>
        <% end %>
      </ol>
    <% end %>

    <p><b>Description:</b> <%= raw @task.description %></p>

    <%= link_to 'Edit', edit_project_task_path(@project,@task) %>

    <% if @task.task_files and @task.task_files.size > 0 %>
      <p><b>Files:</b></p>
    <% end %>
    <div class="task_file_list">
      <% @task.task_files.each do |task_file|  %>
        <div>
          <p>
            <%= link_to task_file.file_name, task_file.file.url %>&nbsp;
            <%= link_to(image_tag("bt_mais.gif"),"javascript:void(0)", {:onclick => "toggleTaskDescription(this);", :class => "mais"}) if task_file.description != nil %>
          </p>
          <div class="task_file_description" style="display:none;">
            <%= task_file.description %>
          </div>
        </div>
      <% end %>
    </div>
  </section>

  <aside>
    <% if @task.comments.any? %>
      <h2>Comments</h2>

      <ul class="thread">
        <% @comments.each do |c| %>
          <li>
            <%= link_to 'Destroy', project_task_comment_path(@project, @task, c), confirm: 'Are you sure?', method: :delete, :class => "destroy" if c.user == current_user%>
            <em><%= c.user.email %> said <%= time_ago_in_words c.updated_at %></em>
            <%= raw c.description.html_safe %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <h2>No comments yet!</h2>
      <h3>User the form below to start posting...</h3>
    <% end %>

    <%= form_for [@project, @task, @comment] do |c| %>
      <%= c.label :description %><br />
      <%= c.text_area :description %>
      <%= c.submit %>
    <% end %>
  </aside>
</article>

app/views/tasks/start.js.erb
$("#task-<%= @task.id%>").replaceWith("<%= escape_javascript render(:partial => 'tasks/task_item', :locals => { :task => @task }) %>");

app/views/tasks/stop.js.erb
$("#task-<%= @task.id%>").replaceWith("<%= escape_javascript render(:partial => 'tasks/task_item', :locals => { :task => @task }) %>");