config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  default_url_options host: 'http://localhost'
  devise_for :users

  resources :projects do
    resources :tasks, :except => [:index, :new] do
      match "change_status/:status" => 'tasks#change_status', :as => :change_status, :on => :member, :via => :all
      match 'start' => 'tasks#start', :as => 'start', :on => :member, :via => :all
      match 'stop' => 'tasks#stop', :as => 'stop', :on => :member, :via => :all
      resources :comments, :only => [:create, :destroy]
    end
  end


  root :to => 'projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tasks, :dependent => :destroy

  validates :name,  :presence => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, :only => [:show, :edit, :update, :destroy]
  before_action :load_users, :load_estimates, :load_status, :load_types, :only => [:show]
  before_action :load_other_users, :only => [:new, :edit]

  def index
    @projects = current_user.projects
  end

  def show
    @new_task = @project.tasks.new
    @tasks = @project.tasks.all
    @task_todo = @project.tasks.todo.order("updated_at DESC")
    @task_scheduled = @project.tasks.scheduled.order("updated_at DESC")
    @task_current = @project.tasks.current.order("updated_at DESC")
    @task_done = @project.tasks.done.order("updated_at DESC")
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = Project.new(project_params)
    @project.users << current_user
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private

  def load_project
    @project = current_user.projects.find(params[:id])
  end

  def load_other_users
    @users = User.without(current_user)
  end

  def project_params
    params.require(:project).permit(:name, :description, :time_track, :commit)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <fieldset class="inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :time_track, :hint => "(Check this to enable time tracking on each task)" %>
    <% unless @users.blank? %>
      <%= f.association :users, :as => :check_boxes, :collection => @users, :label => "Members"  %>
    <% end %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project #{@project.name}" %>
<h1>Editing project</h1>
<%= link_to '(remove)', @project, :confirm => 'Would you like to delete this project? Are you sure?', :method => :delete %>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% content_for :title, "My Projects" %>
<h3>My Projects - <%= link_to '(+) Create Project', new_project_path %></h3>

<% unless @projects.blank? %>
  <ul id="project-list">
    <% @projects.each do |project| %>
      <li>
        <%= link_to project.name, project_path(project.id) %>
        <%= content_tag :p, project.description unless project.description.blank? %>
        <ul>
          <% project.users.each do |project_user| %>
            <li><%= show_user_avatar(project_user) %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You don't have any projects. <%= link_to 'Create', new_project_path %> your first project!</p>
<% end %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% content_for :title, @project.name %>
<article id="project-show">
  <header>
    <h1><%= @project.name %> <span>(<%= link_to 'edit', edit_project_path(@project) %>)</span></h1>

    <div class="indent">
      <%= link_to "#", :id => "link_new_task" do %>
        New task
        <%= content_tag :span, "(press n)" %>
      <% end %>
    </div>
    <%= render :partial => 'tasks/form', :locals => {:project => @project, :task => @new_task} %>
  </header>
  <section id="scheduled" class="status-pane">
    <h2>Scheduled:</h2>
    <ul>
      <% @task_scheduled.each do |task| %>
      <%= render :partial => "tasks/task_item", :locals => { :task => task } %>
      <% end %>
    </ul>
  </section>
  <section id="current" class="status-pane current">
    <h2>Current:</h2>
    <ul>
      <% @task_current.each do |task| %>
      <%= render :partial => "tasks/task_item", :locals => { :task => task } %>
      <% end %>
    </ul>
  </section>
  <section id="done" class="status-pane">
    <h2>Done:</h2>
    <ul>
      <% @task_done.each do |task| %>
      <%= render :partial => "tasks/task_item", :locals => { :task => task } %>
      <% end %>
    </ul>
  </section>
  <section id="todo" class="status-pane todo">
    <h2>TODO:</h2>
    <ul>
      <% @task_todo.each do |task| %>
      <%= render :partial => "tasks/task_item", :locals => { :task => task } %>
      <% end %>
    </ul>
  </section>
</article>